using System.Reflection;
using System.Runtime.CompilerServices;
using System.Text;

namespace Beater;

internal class SequenceCodeGenerator
{
    private static readonly Dictionary<Type, object?> _defaultInstances = [];
    private static readonly Type DefaultStrategy = typeof(FollowLeaderStrategy);

    private static string GetIndetation(int level)
    {
        return new string(' ', level * 4);
    }

    public static string GenerateCode(SequenceDesign? seq, string sequenceName, string? description)
    {
        var code = new StringBuilder();
        code.AppendLine("namespace Beater;");
        code.AppendLine();
        code.AppendLine($"public class AutoGenerated_{sequenceName}");
        code.AppendLine("{");
        if (seq?.Leader is null)
        {
            code.AppendLine("}");
            return code.ToString();
        }

        var _ = GetIndetation(1);

        if (description.HasValue())
        {
            code.AppendLine($"{_}/// <summary>");
            code.AppendLine($"{_}/// {description}");
            code.AppendLine($"{_}/// </summary>");
        }
        code.AppendLine($"{_}internal static SequenceDesign GetSequence()");
        var sequenceStrategy = seq.Leader.Strategy;
        var firstSound = seq.FirstSound ?? seq.Leader;
        code.AppendLine($"{_}{{");
        code.AppendLine($"{_}{_}return new SequenceDesign(\"{sequenceName}\")");
        code.AppendLine($"{_}{_}{{");
        if (sequenceStrategy.GetType() != DefaultStrategy || GetPropInitializers(sequenceStrategy).HasValue())
        {
            code.AppendLine($"{_}{_}{_}Strategy = new {sequenceStrategy.GetType().Name}() {{ {GetPropInitializers(sequenceStrategy)} }},");
        }
        var soundBlock = NewSoundCode(firstSound, level: 3);
        if (soundBlock.HasValue())
        {
            code.AppendLine($"{_}{_}{_}Leader = new {Ctor(firstSound)}");
            code.AppendLine(soundBlock);
        }
        else
        {
            code.AppendLine($"{_}{_}{_}Leader = new {Ctor(firstSound)},");
        }
        code.AppendLine($"{_}{_}}};");
        code.AppendLine($"{_}}}");
        code.AppendLine("}"); // end of class

        return code.ToString();
    }

    /// <summary>
    /// Generates cs-file with sequence of followers defined in a JSON file.
    /// May be used to restore a previously saved sequence from JSON.
    /// </summary>
    public static void GenerateCodeFromSequenceJson(string sequenceFilePath, string? description)
    {
        var json = File.ReadAllText(sequenceFilePath);
        var seq = SequenceDesign.FromJson(json);

        var sequenceName = Path.GetFileNameWithoutExtension(sequenceFilePath).Replace("-", "");
        var code = GenerateCode(seq, sequenceName, description);

        SaveFile(sequenceName, code);
    }

    public static string NewSequenceName() => $"seq{DateTime.Now:yyyyMMddHHmmss}";

    /// <summary>
    /// Generates cs-file with a loop where each sound is delayed after another by a number of milliseconds.
    /// May be used to re-create a sequence from a recorded audio loop with known intervals between its sounds.
    /// </summary>
    public static string GenerateCodeFromDelays(string soundName, params int[] delays)
    {
        if (delays.Length == 0)
        {
            return "";
        }

        var sequenceName = NewSequenceName();
        var totalTime = delays.Sum();
        var iterationsCount = 4;
        var loop = new Metronome() { Strategy = new RepeatStrategy { Count = iterationsCount, Interval = totalTime } };
        var seq = new SequenceDesign(sequenceName) { Leader = loop };
        Sound? previousSound = null;


        delays = [.. delays.Prepend(0)]; // the first sound should always sound without delay

        foreach (var delay in delays)
        {
            var sound = new Sound(soundName) { Strategy = new FollowLeaderStrategy { DelayAfterLeader = delay } };
            var followers = previousSound?.Followers ?? loop.Followers;
            followers.Add(sound);

            previousSound = sound;
        }

        var code = GenerateCode(seq, sequenceName, seq.ToString());
        SaveFile(sequenceName, code);

        return code;
    }

    private static string? NewSoundCode(Sound sound, int level)
    {
        var _ = GetIndetation(level);
        if (sound.Followers.Count == 0)
        {
            // no followers, one-liner
            var strategyCode = StrategyCode(sound.Strategy);
            if (strategyCode.HasValue())
            {
                return $"{_}{{ Strategy = new {sound.Strategy.GetType().Name}() {{{strategyCode}}}}},";
            }
            return null; // default FollowLeaderStrategy with no followers — no initializer block needed
        }

        var code = new StringBuilder();
        code.AppendLine($"{_}{{");
        level++;
        var __ = GetIndetation(level);
        var soundStrategyCode = StrategyCode(sound.Strategy);
        if (soundStrategyCode.HasValue())
        {
            code.AppendLine($"{__}Strategy = new {sound.Strategy.GetType().Name}() {{ {soundStrategyCode} }},");
        }
        code.AppendLine($"{__}Followers = new ()");
        code.AppendLine($"{__}{{");
        level++;
        foreach (var follower in sound.Followers)
        {
            var ___ = GetIndetation(level);
            if (follower.Followers.Count == 0)
            {
                // no more followers, one-liner
                var followerStrategyCode = StrategyCode(follower.Strategy);
                code.Append($"{___}new {Ctor(follower)}");
                if (followerStrategyCode.HasValue())
                {
                    code.Append($" {{ Strategy = new {follower.Strategy.GetType().Name}() {{{followerStrategyCode}}}}}");
                }
                code.AppendLine(",");
            }
            else
            {
                var followerBlock = NewSoundCode(follower, level);
                if (followerBlock.HasValue())
                {
                    code.AppendLine($"{___}new {Ctor(follower)}");
                    code.Append(followerBlock);
                }
                else
                {
                    code.AppendLine($"{___}new {Ctor(follower)},");
                }
            }
        }
        code.AppendLine($"{__}}},"); // end of followers

        code.AppendLine($"{_}}},"); // end of sound
        return code.ToString();
    }

    /// <summary>
    /// Returns property initializers for a strategy, or null if the strategy is a default FollowLeaderStrategy.
    /// </summary>
    private static string? StrategyCode(AbstractStrategy strategy)
    {
        // FollowLeaderStrategy is a default strategy, return it only if it has non default-values
        if (strategy is FollowLeaderStrategy)
        {
            var props = GetPropInitializers(strategy);
            return props.HasValue() ? props : null;
        }
        return GetPropInitializers(strategy);
    }

    private static string GetSoundName(Sound sound)
    {
        return sound.Name.IsNullOrEmpty() ? $"{nameof(NoSound)}.{nameof(NoSound.Name)}" : $"\"{sound.Name}\"";
    }

    private static string Ctor(Sound sound)
    {
        var soundType = sound.GetType();
        if (soundType == typeof(Sound))
        {
            return $"Sound({GetSoundName(sound)})";
        }

        return $"{soundType.Name}()";
    }

    private static IEnumerable<(string name, object? value, object? defaultValue)> GetFieldsAndProperties(object obj)
    {
        var type = obj.GetType();

        object? defaultInstance = GetOrCreateDefaultInstance(type);

        var properties = type.GetProperties(BindingFlags.Public | BindingFlags.Instance | BindingFlags.FlattenHierarchy);
        foreach (var prop in properties)
        {
            if (!prop.CanWrite || prop.SetMethod == null)
            {
                continue; // skip calculated (read-only) properties
            }

            var propValue = prop.GetValue(obj);
            var defaultValue = prop.GetValue(defaultInstance);

            yield return (prop.Name, propValue, defaultValue);
        }

        var fields = type.GetFields(BindingFlags.Public | BindingFlags.Instance | BindingFlags.FlattenHierarchy);
        foreach (var field in fields)
        {
            var fieldValue = field.GetValue(obj);
            var defaultValue = field.GetValue(defaultInstance);
            yield return (field.Name, fieldValue, defaultValue);
        }
    }

    private static object? GetOrCreateDefaultInstance(Type type)
    {
        if (!_defaultInstances.TryGetValue(type, out var defaultInstance))
        {
            defaultInstance = type.GetConstructor(Type.EmptyTypes) != null ? Activator.CreateInstance(type) : null;
            _defaultInstances[type] = defaultInstance;
        }
        return defaultInstance;
    }

    private static string GetPropInitializers(object? obj)
    {
        if (obj is null)
        {
            return "";
        }

        var result = new StringBuilder();
        var properties = GetFieldsAndProperties(obj);
        foreach ((string name, object? value, object? defaultValue) in properties)
        {
            if (value is not null && !value.Equals(defaultValue))
            {
                result.Append($"{name} = {value}, ");
            }
        }

        if (result.Length > 0)
        {
            result.Length -= 2; // remove the trailing comma and space: ", "
        }

        return result.ToString();
    }

    private static string GetSourceCodeDestination([CallerFilePath] string sourceCodePath = "")
    {
        var i = sourceCodePath.LastIndexOf(@"\Src\");
        if (i >= 0)
        {
            var sourcePath = sourceCodePath[..(i + @"\Src\".Length)];
            return Path.Combine(sourcePath, "Sequence", "Sampled");
        }
        i = sourceCodePath.LastIndexOf(@"\Program.cs");
        if (i >= 0)
        {
            var sourcePath = sourceCodePath[..i];
            return Path.Combine(sourcePath, "Src", "Sequence", "Sampled");
        }
        return "";
    }

    private static void SaveFile(string sequenceName, string code)
    {
        var destinationFolder = GetSourceCodeDestination();
        if (!Directory.Exists(destinationFolder))
        {
            Console.WriteLine("Unable to save new sequence code because destination folder doesn't exist: " + destinationFolder);
            return;
        }
        File.WriteAllText(Path.Combine(destinationFolder, $"{sequenceName}.cs"), code.ToString());
    }
}
