using System.Reflection;
using System.Runtime.CompilerServices;
using System.Text;

namespace Beater;

internal class SequenceCodeGenerator
{
    private static string GetIndetation(int level)
    {
        return new string(' ', level * 4);
    }

    public static string GenerateCode(SequenceDesign? seq, string sequenceName, string? description)
    {
        var code = new StringBuilder();
        code.AppendLine("namespace Beater;");
        code.AppendLine();

        if (description.HasValue())
        {
            code.AppendLine("/// <summary>");
            code.AppendLine($"/// {description}");
            code.AppendLine("/// </summary>");
        }
        code.AppendLine($"public class AutoGenerated_{sequenceName}");
        code.AppendLine("{");
        if (seq?.Leader is null)
        {
            code.AppendLine("}");
            return code.ToString();
        }

        var _ = GetIndetation(1);
        code.AppendLine($"{_}internal static Sequence GetSequence()");
        code.AppendLine($"{_}{{");
        code.AppendLine($"{_}{_}return new Sequence");
        code.AppendLine($"{_}{_}{{");
        code.AppendLine($"{_}{_}{_}Leader = new Sound({GetSoundName(seq.Leader)})");
        code.AppendLine(NewSoundCode(seq.Leader, level: 3));
        code.AppendLine($"{_}{_}}};");
        code.AppendLine($"{_}}}");
        code.AppendLine("}"); // end of class

        return code.ToString();
    }

    /// <summary>
    /// Generates cs-file with sequence of followers defined in a JSON file.
    /// May be used to restore a previously saved sequence from JSON.
    /// </summary>
    public static void GenerateCodeFromSequenceJson(string sequenceFilePath, string? description)
    {
        var json = File.ReadAllText(sequenceFilePath);
        var seq = SequenceDesign.FromJson(json);

        var sequenceName = Path.GetFileNameWithoutExtension(sequenceFilePath).Replace("-", "");
        var code = GenerateCode(seq, sequenceName, description);

        SaveFile(sequenceName, code);
    }

    public static string NewSequenceName() => $"seq{DateTime.Now:yyyyMMddHHmmss}";

    /// <summary>
    /// Generates cs-file with a loop where each sound is delayed after another by a number of milliseconds.
    /// May be used to re-create a sequence from a recorded audio loop with known intervals between its sounds.
    /// </summary>
    public static string GenerateCodeFromDelays(string soundName, params int[] delays)
    {
        if (delays.Length == 0)
        {
            return "";
        }

        var sequenceName = NewSequenceName();
        var totalTime = delays.Sum();
        var iterationsCount = 4;
        var loop = new Metronome() { Strategy = new RepeatStrategy { Count = iterationsCount, Interval = totalTime } };
        var seq = new SequenceDesign(sequenceName) { Leader = loop };
        Sound? previousSound = null;


        delays = delays.Prepend(0).ToArray(); // the first sound should always sound without delay

        foreach (var delay in delays)
        {
            var sound = new Sound(soundName) { Strategy = new PlayOnceStrategy { DelayAfterLeader = delay } };
            var followers = previousSound?.Followers ?? loop.Followers;
            followers.Add(sound);

            previousSound = sound;
        }

        var code = GenerateCode(seq, sequenceName, seq.ToString());
        SaveFile(sequenceName, code);

        return code;
    }

    private static string NewSoundCode(Sound sound, int level)
    {
        var _ = GetIndetation(level);
        if (sound.Followers.Count == 0)
        {
            // no followers, one-liner
            return $"{_}{{ Strategy = new {sound.Strategy.GetType().Name}() {{{GetPropInitializers(sound.Strategy)}}}}},";
        }

        var code = new StringBuilder();
        code.AppendLine($"{_}{{");
        level++;
        var __ = GetIndetation(level);
        code.AppendLine($"{__}Strategy = new {sound.Strategy.GetType().Name}() {{ {GetPropInitializers(sound.Strategy)} }},");
        code.AppendLine($"{__}Followers = new ()");
        code.AppendLine($"{__}{{");
        level++;
        foreach (var follower in sound.Followers)
        {
            var ___ = GetIndetation(level);
            if (follower.Followers.Count == 0)
            {
                // no more followers, one-liner
                code.AppendLine($"{___}new Sound({GetSoundName(follower)}) {{ Strategy = new {follower.Strategy.GetType().Name}() {{{GetPropInitializers(follower.Strategy)}}}}},");
            }
            else
            {
                code.AppendLine($"{___}new Sound({GetSoundName(follower)})");
                code.Append(NewSoundCode(follower, level));
            }
        }
        code.AppendLine($"{__}}},"); // end of followers

        code.AppendLine($"{_}}},"); // end of sound
        return code.ToString();
    }

    private static string GetSoundName(Sound sound)
    {
        return sound.Name.IsNullOrEmpty() ? $"{nameof(Sound)}.{nameof(Sound.NoSound)}" : $"\"{sound.Name}\"";
    }

    private static IEnumerable<(string name, object? value, object? defaultValue)> GetFieldsAndProperties(object obj)
    {
        var type = obj.GetType();

        var properties = type.GetProperties(BindingFlags.Public | BindingFlags.Instance | BindingFlags.FlattenHierarchy);
        foreach (var prop in properties)
        {
            var propValue = prop.GetValue(obj);
            var propType = prop.PropertyType;
            var defaultValue = propType.IsValueType ? Activator.CreateInstance(propType) : null;

            yield return (prop.Name, propValue, defaultValue);
        }

        var fields = type.GetFields(BindingFlags.Public | BindingFlags.Instance | BindingFlags.FlattenHierarchy);
        foreach (var field in fields)
        {
            var fieldValue = field.GetValue(obj);
            var fieldType = field.FieldType;
            var defaultValue = fieldType.IsValueType ? Activator.CreateInstance(fieldType) : null;

            yield return (field.Name, fieldValue, defaultValue);
        }
    }

    private static string GetPropInitializers(object? obj)
    {
        if (obj is null)
        {
            return "";
        }

        var result = new StringBuilder();
        var properties = GetFieldsAndProperties(obj);
        foreach ((string name, object? value, object? defaultValue) in properties)
        {
            if (value is not null && !value.Equals(defaultValue))
            {
                result.Append($"{name} = {value}, ");
            }
        }

        if (result.Length > 0)
        {
            result.Length -= 2; // remove the trailing comma and space: ", "
        }

        return result.ToString();
    }

    private static string GetSourceCodeDestination([CallerFilePath] string sourceCodePath = null)
    {
        var i = sourceCodePath.LastIndexOf(@"\Src\");
        if (i >= 0)
        {
            var sourcePath = sourceCodePath.Substring(0, i + @"\Src\".Length);
            return Path.Combine(sourcePath, "Sequences");
        }
        i = sourceCodePath.LastIndexOf(@"\Program.cs");
        if (i >= 0)
        {
            var sourcePath = sourceCodePath.Substring(0, i);
            return Path.Combine(sourcePath, "Src", "Sequences");
        }
        return "";
    }

    private static void SaveFile(string sequenceName, string code)
    {
        var destinationFolder = GetSourceCodeDestination();
        if (!Directory.Exists(destinationFolder))
        {
            Console.WriteLine("Unable to save new sequence code because destination folder doesn't exist: " + destinationFolder);
            return;
        }
        File.WriteAllText(Path.Combine(destinationFolder, $"{sequenceName}.cs"), code.ToString());
    }
}
