using static Beater.SoundExtensions;

namespace Beater.Sampled;

public class AutoGenerated_seq20260508234907
{
    /// <summary>
    /// K            K           K     K     K
    /// </summary>
    internal static SequenceDesign GetSequence()
    {
        var main = new SequenceDesign("main")
        {
            Strategy = new RepeatStrategy() { Count = 4, Interval = 4800 },
            Leader = Chain(
                new Kick() { Tags = ["one"] },
                new Kick() { Tags = ["two"], DelayAfterLeader = 1200 },
                new Kick() { DelayAfterLeader = 1200 },
                new Kick() { DelayAfterLeader = 600 },
                new Kick() { DelayAfterLeader = 600 }
            ),
        };

        var snares1 = GetSnares1();
        snares1.Strategy.DelayAfterLeader = 300;
        snares1.Strategy.PlayEveryXOutOf = "1/2";
        main.Leader.FindByTag("one")?.WithFollower(snares1.Leader);

        var snares2 = GetSnares2();
        snares2.Strategy.DelayAfterLeader = 300;
        snares2.Strategy.PlayEveryXOutOf = "4/4";
        main.Leader.FindByTag("one")?.WithFollower(snares2.Leader);

        var snares3 = GetSnares3();
        snares3.Strategy.DelayAfterLeader = 300;
        snares3.Strategy.PlayEveryXOutOf = "2/4";
        main.Leader.FindByTag("one")?.WithFollower(snares3.Leader);

        return main;
    }

    /// <summary>
    /// S    S            S            S
    /// </summary>
    internal static SequenceDesign GetSnares1()
    {
        return new SequenceDesign("snares1")
        {
            Leader = Chain(
                new Snare(),
                new Snare() { DelayAfterLeader = 120 },
                new Snare() { DelayAfterLeader = 320 },
                new Snare() { DelayAfterLeader = 320 }
            ),
        };
    }

    /// <summary>
    /// S  S      S
    /// </summary>
    internal static SequenceDesign GetSnares2()
    {
        return new SequenceDesign("snares2")
        {
            Leader = Chain(
                new Snare(),
                new Snare() { DelayAfterLeader = 280 },
                new Snare() { DelayAfterLeader = 450 }
            ),
        };
    }

    /// <summary>
    /// S  S      S  S      S
    /// </summary>
    internal static SequenceDesign GetSnares3()
    {
        return new SequenceDesign("snares3")
        {
            Leader = Chain(
                new Snare(),
                new Snare() { DelayAfterLeader = 120 },
                new Snare() { DelayAfterLeader = 320 },
                new Snare() { DelayAfterLeader = 120 },
                new Snare() { DelayAfterLeader = 320 }
            ),
        };
    }
}
