using static Beater.SoundExtensions;

namespace Beater.Sampled;

/// <summary>
/// P  P   P P P   P   P
/// </summary>
public class AutoGenerated_seq202505151422
{
    internal static SequenceDesign GetSequence()
    {
        return new SequenceDesign(nameof(AutoGenerated_seq202505151422))
        {
            Leader = new Metronome()
            {
                Strategy = new RepeatStrategy() { Count = 4, Interval = 2500 },
                Followers = [Chain(
                    new Kick { },
                    new Kick { DelayAfterLeader = 200 },
                    new Kick { DelayAfterLeader = 300 },
                    new Kick { DelayAfterLeader = 100 },
                    new Kick { DelayAfterLeader = 100 },
                    new Kick { DelayAfterLeader = 300 },
                    new Kick { DelayAfterLeader = 300 }
                )]
            },
        };
    } 
}
