namespace Beater;

public class AutoGenerated_seq202512212337
{
    internal static SequenceDesign GetSequence2()
    {
        return new SequenceDesign(nameof(AutoGenerated_seq202512212337))
        {
            Leader = new Metronome()
            {
                Strategy = new RepeatStrategy() { Count = 4, Interval = 6000, PlayEveryX = 1 },
                Followers = [
                    new Sound("ts9") { Strategy = new PlayOnceStrategy()},
                    new Sound("ts5") { Strategy = new FollowPreviousSoundStrategy() {DelayAfterLeader = 650 }},
                    new Sound("ts2") { Strategy = new FollowPreviousSoundStrategy() {DelayAfterLeader = 500 }},
                    new Sound("ts5") { Strategy = new FollowPreviousSoundStrategy() {DelayAfterLeader = 650 }},
                    new Sound("ts8") { Strategy = new FollowPreviousSoundStrategy() {DelayAfterLeader = 610 }},
                    new Sound("ts5") { Strategy = new FollowPreviousSoundStrategy() {DelayAfterLeader = 650 }},
                    new Sound("ts5") { Strategy = new FollowPreviousSoundStrategy() {DelayAfterLeader = 200 }},
                    new Sound("ts5") { Strategy = new FollowPreviousSoundStrategy() {DelayAfterLeader = 200 }},
                    new Sound("ts2") { Strategy = new FollowPreviousSoundStrategy() {DelayAfterLeader = 150 }},
                    new Sound("ts9") { Strategy = new FollowPreviousSoundStrategy() {DelayAfterLeader = 100 }},
                    new Sound("ts5") { Strategy = new FollowPreviousSoundStrategy() {DelayAfterLeader = 850 }},
                    new Kick { Strategy = new FollowPreviousSoundStrategy()  {DelayAfterLeader = 300 }},
                ]
            },

        };
    }
    internal static SequenceDesign GetSequence3()
    {
        return new SequenceDesign(nameof(AutoGenerated_seq202512212337))
        {
            Name = "se3",
            Duration = 5200,
            Leader = new Metronome()
            {
                Strategy = new RepeatStrategy() { Count = 1, Interval = 5200, PlayEveryX = 1 }, // count was changed from 4 to 1
                Followers = [
                        new Kick { Strategy = new FollowPreviousSoundStrategy() {}},
                        new Sound("ts9") { Strategy = new FollowPreviousSoundStrategy() {}},
                        new Sound("ts1") { Strategy = new FollowPreviousSoundStrategy() {DelayAfterLeader = 640}},
                        new Sound("ts5") { Strategy = new FollowPreviousSoundStrategy() {}},
                        new Sound("ts5") { Strategy = new FollowPreviousSoundStrategy() {DelayAfterLeader = 100}},
                        new Sound("ts6") { Strategy = new FollowPreviousSoundStrategy() {DelayAfterLeader = 560}},
                        new Sound("ts2") { Strategy = new FollowPreviousSoundStrategy() {}},
                        new Sound("ts5") { Strategy = new FollowPreviousSoundStrategy() {DelayAfterLeader = 680}},
                        new Sound("ts5") { Strategy = new FollowPreviousSoundStrategy() {DelayAfterLeader = 200}},
                        new Kick { Strategy = new FollowPreviousSoundStrategy() {DelayAfterLeader = 400}},
                        new Sound("ts6") { Strategy = new FollowPreviousSoundStrategy() {}},
                        new Sound("ts6") { Strategy = new FollowPreviousSoundStrategy() {DelayAfterLeader = 630}},
                        new Sound("ts5") { Strategy = new FollowPreviousSoundStrategy() {DelayAfterLeader = 700}},
                ]
            },
        };
    }
}
