using static Beater.SoundExtensions;

namespace Beater.Sampled;

public class AutoGenerated_seq202512212337
{
    internal static SequenceDesign GetSequence2()
    {
        return new SequenceDesign(nameof(AutoGenerated_seq202512212337))
        {
            Leader = new Metronome()
            {
                Strategy = new RepeatStrategy() { Count = 4, Interval = 6000, PlayEveryX = 1 },
                Followers = [Chain(
                    new SoundDesign("ts9") { },
                    new SoundDesign("ts5") { DelayAfterLeader = 650 },
                    new SoundDesign("ts2") { DelayAfterLeader = 500 },
                    new SoundDesign("ts5") { DelayAfterLeader = 650 },
                    new SoundDesign("ts8") { DelayAfterLeader = 610 },
                    new SoundDesign("ts5") { DelayAfterLeader = 650 },
                    new SoundDesign("ts5") { DelayAfterLeader = 200 },
                    new SoundDesign("ts5") { DelayAfterLeader = 200 },
                    new SoundDesign("ts2") { DelayAfterLeader = 150 },
                    new SoundDesign("ts9") { DelayAfterLeader = 100 },
                    new SoundDesign("ts5") { DelayAfterLeader = 850 },
                    new Kick { DelayAfterLeader = 300 }
                )]
            },

        };
    }
    internal static SequenceDesign GetSequence3()
    {
        return new SequenceDesign("se3")
        {
            Duration = 5200,
            Leader = new Metronome()
            {
                Strategy = new RepeatStrategy() { Count = 1, Interval = 5200, PlayEveryX = 1 }, // count was changed from 4 to 1
                Followers = [Chain(
                        new Kick { },
                        new SoundDesign("ts9") { },
                        new SoundDesign("ts1") { DelayAfterLeader = 640 },
                        new SoundDesign("ts5") { DelayAfterLeader = 650 },
                        new SoundDesign("ts5") { DelayAfterLeader = 100 },
                        new SoundDesign("ts6") { DelayAfterLeader = 560 },
                        new SoundDesign("ts2") { DelayAfterLeader = 500 },
                        new SoundDesign("ts5") { DelayAfterLeader = 680 },
                        new SoundDesign("ts5") { DelayAfterLeader = 200 },
                        new Kick { DelayAfterLeader = 400 },
                        new SoundDesign("ts6") { DelayAfterLeader = 630 },
                        new SoundDesign("ts5") { DelayAfterLeader = 700 }
                )]
            },
        };
    }
}
