namespace Beater.Sampled;

/// <summary>
/// P  P   P P P   P   P
/// </summary>
public class AutoGenerated_seq202505151422
{
    internal static SequenceDesign GetSequence()
    {
        return new SequenceDesign(nameof(AutoGenerated_seq202505151422))
        {
            Leader = new Metronome()
            {
                Strategy = new RepeatStrategy() { Count = 4, Interval = 2500, PlayEveryX = 1 },
                Followers = [
                    new Kick { Strategy = new FollowPreviousSoundStrategy() {PlayEveryX = 1}},
                    new Kick { Strategy = new FollowPreviousSoundStrategy() {DelayAfterLeader = 200, PlayEveryX = 1}},
                    new Kick { Strategy = new FollowPreviousSoundStrategy() {DelayAfterLeader = 300, PlayEveryX = 1}},
                    new Kick { Strategy = new FollowPreviousSoundStrategy() {DelayAfterLeader = 100, PlayEveryX = 1}},
                    new Kick { Strategy = new FollowPreviousSoundStrategy() {DelayAfterLeader = 100, PlayEveryX = 1}},
                    new Kick { Strategy = new FollowPreviousSoundStrategy() {DelayAfterLeader = 300, PlayEveryX = 1}},
                    new Kick { Strategy = new FollowPreviousSoundStrategy() {DelayAfterLeader = 300, PlayEveryX = 1}},
                ]
            },
        };
    } 
}
