namespace Beater;

public class SlowBeat
{
    internal static SequenceDesign WithMovingSoundBetweenGroups()
    {
        var count = 0;
        var sequence = new SequenceDesign(nameof(SlowBeat));
        for (int i = 4; i > 0; i--)
        {
            count++;
            var slowBeat = Minimal.SlowBeat1WithoutRepeats();
            slowBeat.Name += $".{count}";
            slowBeat.Leader.FindByTag($"group-{i}")?.Followers.Add(
                new Sound("ts1", "ts9") // play ts1 + ts9 at the same time when group-X begins to close
            );
            sequence.Append(slowBeat);
        }

        return sequence;
    }

    internal static SequenceDesign WithMovingSequenceBetweenGroups()
    {
        var sequence = new SequenceDesign(nameof(SlowBeat));
        for (int i = 1; i <= 3; i++)
        {
            var slowBeat1 = Minimal.SlowBeat1WithoutRepeatsK1S1();
            slowBeat1.Name += $".{i}";
            // var slowBeat2 = Minimal.SlowBeat1WithoutRepeats();
            // slowBeat1.Append(slowBeat2);
            var another = AutoGenerated_seq202512212337.GetSequence3();
            another.Name += $".{i}";

            slowBeat1.Leader.FindByTag($"group-{i}")?.Followers.Add(
                another.Leader
            );
            sequence.Append(slowBeat1);
        }

        return sequence;
    }
}
