using static Beater.SoundExtensions;

namespace Beater.Sampled;

public class SlowBeat
{
    internal static SequenceDesign WithMovingSoundBetweenGroups()
    {
        var count = 0;
        var sequence = new SequenceDesign(nameof(SlowBeat));
        for (int i = 4; i > 0; i--)
        {
            count++;
            var slowBeat = Minimal.SlowBeat1WithoutRepeats();
            slowBeat.Name += $".{count}";
            slowBeat.Leader.FindByTag($"group-{i}")?.Followers.Add(
                new Sound("ts1", "ts9") // play ts1 + ts9 at the same time when group-X begins to close
            );
            sequence.Append(slowBeat);
        }

        return sequence;
    }

    internal static SequenceDesign WithMovingSequenceBetweenGroups()
    {
        var sequence = new SequenceDesign(nameof(SlowBeat));
        for (int i = 1; i <= 3; i++)
        {
            var slowBeat1 = Minimal.SlowBeat1WithoutRepeatsK1S1();
            slowBeat1.Name += $".{i}";
            // var slowBeat2 = Minimal.SlowBeat1WithoutRepeats();
            // slowBeat1.Append(slowBeat2);
            var another = AutoGenerated_seq202512212337.GetSequence3();
            another.Name += $".{i}";

            slowBeat1.Leader.FindByTag($"group-{i}")?.Followers.Add(
                another.Leader
            );
            sequence.Append(slowBeat1);
        }

        return sequence;
    }

    /// <summary>
    /// K   S  K     K        K     S  K     K |||
    /// </summary>
    internal static SequenceDesign GetSequence1()
    {
        return new SequenceDesign("SlowBeat1")
        {
            Strategy = new RepeatStrategy() { Count = 4, Interval = 4000 },
            Leader = new Kick()
            {
                Followers = [Chain(
                    new Snare() { DelayAfterLeader = 300 },
                    new Kick()  { DelayAfterLeader = 200 },
                    new Kick()  { DelayAfterLeader = 500 },
                    new Kick()  { DelayAfterLeader = 800 },
                    new Snare() { DelayAfterLeader = 500 },
                    new Kick()  { DelayAfterLeader = 200 },
                    new Kick()  { Tags = ["end"], DelayAfterLeader = 500, }
                )],
            },
        };
    }

    /// <summary>
    /// K   S  K   S  K     S     K
    /// </summary>
    internal static SequenceDesign GetSequence2()
    {
        return new SequenceDesign("SlowBeat2")
        {
            Strategy = new RepeatStrategy() { Count = 4, Interval = 3400 },
            Leader = new Kick()
            {
                Followers = [Chain(
                    new Snare { DelayAfterLeader = 300 },
                    new Kick  { DelayAfterLeader = 200 },
                    new Snare { DelayAfterLeader = 300 },
                    new Kick  { DelayAfterLeader = 200 },
                    new Snare { DelayAfterLeader = 500 },
                    new Kick  { DelayAfterLeader = 500 }
                )],
            },
        };
    }

    /// <summary>
    /// K   K  K     S     K   K  K   K  K     S     K
    /// </summary>
    internal static SequenceDesign GetSequence3()
    {
        return new SequenceDesign("SlowBeat3")
        {
            Strategy = new RepeatStrategy() { Count = 4, Interval = 4800 },
            Leader = new Kick()
            {
                Followers = [Chain(
                    new Kick()  { DelayAfterLeader = 300 },
                    new Kick()  { DelayAfterLeader = 200 },
                    new Snare() { DelayAfterLeader = 500 },
                                                         
                    new Kick()  { DelayAfterLeader = 500 },
                    new Kick()  { DelayAfterLeader = 300 },
                    new Kick()  { DelayAfterLeader = 200 },
                    new Kick()  { DelayAfterLeader = 300 },
                    new Kick()  { DelayAfterLeader = 200 },
                                                         
                    new Snare() { DelayAfterLeader = 500 },
                    new Kick()  { DelayAfterLeader = 500 }
                )],
            },
        };
    }

    /// <summary>
    /// K  K  K    S    K  K  K        S        K  K  K    S    K  K  K     K    S
    /// </summary>
    internal static SequenceDesign GetSequence4()
    {
        return new SequenceDesign("SlowBeat4")
        {
            Strategy = new RepeatStrategy() { Count = 4, Interval = 6400 },
            Leader = new Kick()
            {
                Followers = [Chain(
                    new Kick  { DelayAfterLeader = 200 },
                    new Kick  { DelayAfterLeader = 200 },
                    new Snare { DelayAfterLeader = 400 },
                    new Kick  { DelayAfterLeader = 400 },
                    new Kick  { DelayAfterLeader = 200 },
                    new Kick  { DelayAfterLeader = 200 },
                    new Snare { DelayAfterLeader = 800 },
                                                       
                    new Kick  { DelayAfterLeader = 800 },
                    new Kick  { DelayAfterLeader = 200 },
                    new Kick  { DelayAfterLeader = 200 },
                    new Snare { DelayAfterLeader = 400 },
                    new Kick  { DelayAfterLeader = 400 },
                    new Kick  { DelayAfterLeader = 200 },
                    new Kick  { DelayAfterLeader = 200 },
                    new Kick  { DelayAfterLeader = 420 },
                    new Snare { DelayAfterLeader = 400 }
                )],
            },
        };
    }

    /// <summary>
    /// K  K  K    S    K  K    K    K  S
    /// </summary>
    internal static SequenceDesign GetSequence5()
    {
        return new SequenceDesign("SlowBeat5")
        {
            Strategy = new RepeatStrategy() { Count = 4, Interval = 3200 },
            Leader = new Kick
            {
                Followers = [Chain(
                    new Kick  { DelayAfterLeader = 200 },
                    new Kick  { DelayAfterLeader = 200 },
                    new Snare { DelayAfterLeader = 400 },

                    new Kick  { DelayAfterLeader = 400 },
                    new Kick  { DelayAfterLeader = 200 },
                    new Kick  { DelayAfterLeader = 400 },
                    new Kick  { DelayAfterLeader = 400 },
                    new Snare { DelayAfterLeader = 200 }
                )],
            },
        };
    }
}
