using Beater;

namespace Tests;

public class SequenceCodeGeneratorTests(ITestOutputHelper output) : TestBase(output)
{
    // -------------------------------------------------------------------------
    // Null / empty leader — minimal class body
    // -------------------------------------------------------------------------

    [Fact]
    public void GenerateCode_NullSequence_OutputsMinimalClassWithEmptyBody()
    {
        // arrange / act
        var result = SequenceCodeGenerator.GenerateCode(null, "MyBeat", null);

        // assert
        result.Should().Contain("namespace Beater;");
        result.Should().Contain("public class AutoGenerated_MyBeat");
        result.Should().NotContain("GetSequence");
        result.Should().NotContain("Leader");
    }

    // -------------------------------------------------------------------------
    // Description → XML doc comment
    // -------------------------------------------------------------------------

    [Fact]
    public void GenerateCode_WithDescription_EmitsXmlDocComment()
    {
        // arrange
        var seq = new SequenceDesign("test")
        {
            Leader = new Kick(),
        };

        // act
        var result = SequenceCodeGenerator.GenerateCode(seq, "test", "My description");

        // assert
        result.Should().ContainAll(
            "/// <summary>",
            "/// My description",
            "/// </summary>"
        );
    }

    // -------------------------------------------------------------------------
    // Simple sequence — single sound with default PlayOnceStrategy
    // -------------------------------------------------------------------------

    [Fact]
    public void GenerateCode_LeaderWithDefaultPlayOnceStrategy_EmitsNoInitializerBlock()
    {
        // arrange — Kick with default PlayOnceStrategy (no custom props)
        var seq = new SequenceDesign("test")
        {
            Leader = new Kick(),
        };

        // act
        var result = SequenceCodeGenerator.GenerateCode(seq, "test", null);

        // assert — Leader line ends with a comma and has no initializer block
        result.Should().Contain("Leader = new Kick(),");
        result.Should().NotContain("Strategy = new PlayOnceStrategy");
    }

    // -------------------------------------------------------------------------
    // Sound with custom PlayOnceStrategy → inline { Strategy = ... } block
    // -------------------------------------------------------------------------

    [Fact]
    public void GenerateCode_LeaderWithCustomPlayOnceStrategy_EmitsInlineStrategyBlock()
    {
        // arrange
        var seq = new SequenceDesign("test")
        {
            Leader = new Kick()
            {
                Strategy = new FollowLeaderStrategy { DelayAfterLeader = 300 },
            },
        };

        // act
        var result = SequenceCodeGenerator.GenerateCode(seq, "test", null);

        // assert
        result.Should().Contain("Strategy = new PlayOnceStrategy()");
        result.Should().Contain("DelayAfterLeader = 300");
    }

    // -------------------------------------------------------------------------
    // SequenceDesign-level RepeatStrategy → emitted on SequenceDesign
    // -------------------------------------------------------------------------

    [Fact]
    public void GenerateCode_SequenceDesignRepeatStrategy_EmittedWithCountAndInterval()
    {
        // arrange
        var seq = new SequenceDesign("test")
        {
            Strategy = new RepeatStrategy { Count = 4, Interval = 2000 },
            Leader = new Metronome(),
        };

        // act
        var result = SequenceCodeGenerator.GenerateCode(seq, "test", null);

        // assert
        result.Should().ContainAll(
            "Strategy = new RepeatStrategy()",
            "Count = 4",
            "Interval = 2000"
        );
    }

    // -------------------------------------------------------------------------
    // Default FollowPreviousSoundStrategy on SequenceDesign → added with default props
    // -------------------------------------------------------------------------

    [Fact]
    public void GenerateCode_DefaultFollowPreviousSoundStrategyOnSequenceDesign_EmittedWithDefaultProps()
    {
        // arrange — no explicit strategy set: SequenceStart uses FollowPreviousSoundStrategy by default
        var seq = new SequenceDesign("test")
        {
            Leader = new Kick(),
        };

        // act
        var result = SequenceCodeGenerator.GenerateCode(seq, "test", null);

        // assert
        result.Should().Contain("FollowPreviousSoundStrategy() { ShouldFollowSameSequence = False");
    }

    // -------------------------------------------------------------------------
    // Sound with followers → Followers = new () { ... } block
    // -------------------------------------------------------------------------

    [Fact]
    public void GenerateCode_LeaderWithFollowers_EmitsFollowersBlock()
    {
        // arrange
        var seq = new SequenceDesign("test")
        {
            Leader = new Metronome()
            {
                Followers =
                [
                    new Kick(),
                    new Snare(),
                ],
            },
        };

        // act
        var result = SequenceCodeGenerator.GenerateCode(seq, "test", null);

        // assert
        result.Should().ContainAll(
            "Followers = new ()",
            "new Kick(),",
            "new Snare(),"
        );
    }

    // -------------------------------------------------------------------------
    // Follower with default strategy → just new Kick(), (no initializer)
    // -------------------------------------------------------------------------

    [Fact]
    public void GenerateCode_FollowerWithDefaultStrategy_EmitsNoInitializerBlock()
    {
        // arrange
        var seq = new SequenceDesign("test")
        {
            Leader = new Metronome()
            {
                Followers =
                [
                    new Kick(),
                ],
            },
        };

        // act
        var result = SequenceCodeGenerator.GenerateCode(seq, "test", null);

        // assert — follower appears as a plain one-liner with no initializer
        result.Should().Contain("new Kick(),");
        // there should be no Strategy block anywhere in the output
        result.Should().NotContain("Strategy = new PlayOnceStrategy");
    }

    // -------------------------------------------------------------------------
    // Follower with custom strategy → inline { Strategy = ... }
    // -------------------------------------------------------------------------

    [Fact]
    public void GenerateCode_FollowerWithCustomStrategy_EmitsInlineStrategyOnFollower()
    {
        // arrange
        var seq = new SequenceDesign("test")
        {
            Leader = new Metronome()
            {
                Followers =
                [
                    new Snare() { Strategy = new FollowLeaderStrategy { DelayAfterLeader = 500 } },
                ],
            },
        };

        // act
        var result = SequenceCodeGenerator.GenerateCode(seq, "test", null);

        // assert
        result.Should().ContainAll(
            "new Snare()",
            "Strategy = new PlayOnceStrategy()",
            "DelayAfterLeader = 500"
        );
    }

    // -------------------------------------------------------------------------
    // Generic Sound type → new Sound("name")
    // -------------------------------------------------------------------------

    [Fact]
    public void GenerateCode_GenericSoundType_EmitsSoundCtorWithName()
    {
        // arrange
        var seq = new SequenceDesign("test")
        {
            Leader = new Sound("hi-hat"),
        };

        // act
        var result = SequenceCodeGenerator.GenerateCode(seq, "test", null);

        // assert
        result.Should().Contain("new Sound(\"hi-hat\")");
    }

    // -------------------------------------------------------------------------
    // Integration — full sequence with strategy + leader + nested followers
    // -------------------------------------------------------------------------

    [Fact]
    public void GenerateCode_FullSequence_EmitsCorrectStructure()
    {
        // arrange
        var seq = new SequenceDesign("test")
        {
            Strategy = new RepeatStrategy { Count = 4, Interval = 2000 },
            Leader = new Metronome()
            {
                Followers =
                [
                    new Kick(),
                    new Snare() { Strategy = new FollowLeaderStrategy { DelayAfterLeader = 500 } },
                ],
            },
        };

        // act
        var result = SequenceCodeGenerator.GenerateCode(seq, "test", null);

        // assert — namespace and class
        result.Should().Contain("namespace Beater;");
        result.Should().Contain("public class AutoGenerated_test");

        // assert — method signature
        result.Should().Contain("internal static SequenceDesign GetSequence()");
        result.Should().Contain("return new SequenceDesign(\"test\")");

        // assert — sequence-level strategy
        result.Should().ContainAll(
            "Strategy = new RepeatStrategy()",
            "Count = 4",
            "Interval = 2000"
        );

        // assert — leader
        result.Should().Contain("Leader = new Metronome()");

        // assert — followers block with mixed strategies
        result.Should().ContainAll(
            "Followers = new ()",
            "new Kick(),",
            "new Snare()",
            "DelayAfterLeader = 500"
        );
    }
}
