using System.Reflection;
using System.Text;
using System.Text.RegularExpressions;

namespace Beater;

internal class SequenceCodeGenerator
{
    public static string GenerateCode(Sequence? seq, string sequenceName, string? description) =>
$@"namespace Beater;
/// <summary>
/// ""{description}""
/// </summary>
public class AutoGenerated_{sequenceName}
{{
    internal static Sequence GetSequence()
    {{
        {GenerateCode(seq)}
        return sequence;
    }}
}}";

    public static string GenerateCode(Sequence? seq)
    {
        if (seq?.Leader is null)
        {
            return "";
        }

        var code = new StringBuilder();
        code.AppendLine($@"
        var sequence = new Sequence
        {{
            Leader = {NewSoundCode(seq.Leader, level: 0)}
        }};");

        return code.ToString();
    }

    private static string NewSoundCode(Sound sound, int level)
    {
        var indent = new string(' ', level * 8);
        var code = new StringBuilder();
        code.AppendLine($@"        {indent}new Sound(""{sound.Name}"")
        {indent}{{
        {indent}    Strategy = new {sound.Strategy.GetType().Name}() {{ {GetPropInitializers(sound.Strategy)} }},
        {indent}    Followers = new ()
        {indent}    {{");

        foreach (var follower in sound.Followers)
        {
            level++;
            code.AppendLine(NewSoundCode(follower, level));
        }

        code.AppendLine($@"
        {indent}    }}
        {indent}}}");

        return WithoutEmptyLines(code.ToString());
    }

    private static string WithoutEmptyLines(string source)
    {
        return Regex.Replace(source, "\r\n\r\n\r\n", "\r\n");
    }

    private static IEnumerable<(string name, object? value, object? defaultValue)> GetFieldsAndProperties(object obj)
    {
        var type = obj.GetType();

        var properties = type.GetProperties(BindingFlags.Public | BindingFlags.Instance | BindingFlags.FlattenHierarchy);
        foreach (var prop in properties)
        {
            var propValue = prop.GetValue(obj);
            var propType = prop.PropertyType;
            var defaultValue = propType.IsValueType ? Activator.CreateInstance(propType) : null;

            yield return (prop.Name, propValue, defaultValue);
        }

        var fields = type.GetFields(BindingFlags.Public | BindingFlags.Instance | BindingFlags.FlattenHierarchy);
        foreach (var field in fields)
        {
            var fieldValue = field.GetValue(obj);
            var fieldType = field.FieldType;
            var defaultValue = fieldType.IsValueType ? Activator.CreateInstance(fieldType) : null;

            yield return (field.Name, fieldValue, defaultValue);
        }
    }

    private static string GetPropInitializers(object? obj)
    {
        if (obj is null)
        {
            return "";
        }

        var result = new StringBuilder();
        var properties = GetFieldsAndProperties(obj);
        foreach ((string name, object? value, object? defaultValue) in properties)
        {
            if (value is not null && !value.Equals(defaultValue))
            {
                result.Append($"{name} = {value}, ");
            }
        }

        if (result.Length > 0)
        {
            result.Length -= 2; // remove the trailing comma and space: ", "
        }

        return result.ToString();
    }
}
