using System.Reflection;
using System.Runtime.CompilerServices;
using System.Text;
using System.Text.RegularExpressions;

namespace Beater;

internal class SequenceCodeGenerator
{
    public static string GenerateCode(Sequence? seq, string sequenceName, string? description) =>
$@"namespace Beater;
/// <summary>
/// ""{description}""
/// </summary>
public class AutoGenerated_{sequenceName}
{{
    internal static Sequence GetSequence()
    {{
        {GenerateCode(seq)}
        return sequence;
    }}
}}";

    /// <summary>
    /// Generates cs-file with sequence of followers defined in a JSON file.
    /// May be used to restore a previously saved sequence from JSON.
    /// </summary>
    public static void GenerateCodeFromSequenceJson(string sequenceFilePath, string? description)
    {
        var json = File.ReadAllText(sequenceFilePath);
        var seq = Sequence.FromJson(json);

        var sequenceName = Path.GetFileNameWithoutExtension(sequenceFilePath).Replace("-", "");
        var code = GenerateCode(seq, sequenceName, description);

        SaveFile(sequenceName, code);
    }

    /// <summary>
    /// Generates cs-file with a loop where each sound is delayed after another by a number of milliseconds.
    /// May be used to re-create a sequence from a recorded audio loop with known intervals between its sounds.
    /// </summary>
    public static string GenerateCodeFromDelays(string soundName, params int[] delays)
    {
        if (delays.Length == 0)
        {
            return "";
        }

        var totalTime = delays.Sum();
        var iterationsCount = 4;
        var loop = new Sound("") { Strategy = new RepeatStrategy { Count = iterationsCount, Interval = totalTime } };
        var seq = new Sequence { Leader = loop };
        Sound? previousSound = null;


        delays = delays.Prepend(0).ToArray(); // the first sound should always sound without delay

        foreach (var delay in delays)
        {
            var sound = new Sound(soundName);
            sound.Strategy = new PlayOnceStrategy { DelayAfterLeader = delay };

            var followers = previousSound?.Followers ?? loop.Followers;
            followers.Add(sound);

            previousSound = sound;
        }

        var sequenceName = $"seq{DateTime.Now:yyyyMMddHHmm}";
        var code = GenerateCode(seq, sequenceName, seq.ToString());
        SaveFile(sequenceName, code);

        return code;
    }

    private static string GenerateCode(Sequence? seq)
    {
        if (seq?.Leader is null)
        {
            return "";
        }

        var code = new StringBuilder();
        code.AppendLine($@"
        var sequence = new Sequence
        {{
            Leader = {NewSoundCode(seq.Leader, level: 0)}
        }};");

        return code.ToString();
    }

    private static string NewSoundCode(Sound sound, int level)
    {
        var indent = new string(' ', level * 8);
        var code = new StringBuilder();
        code.AppendLine($@"        {indent}new Sound(""{sound.Name}"")
        {indent}{{
        {indent}    Strategy = new {sound.Strategy.GetType().Name}() {{ {GetPropInitializers(sound.Strategy)} }},
        {indent}    Followers = new ()
        {indent}    {{");

        foreach (var follower in sound.Followers)
        {
            level++;
            code.AppendLine(NewSoundCode(follower, level));
        }

        code.AppendLine($@"
        {indent}    }}
        {indent}}}");

        return WithoutEmptyLines(code.ToString());
    }

    private static string WithoutEmptyLines(string source)
    {
        return Regex.Replace(source, "\r\n\r\n\r\n", "\r\n");
    }

    private static IEnumerable<(string name, object? value, object? defaultValue)> GetFieldsAndProperties(object obj)
    {
        var type = obj.GetType();

        var properties = type.GetProperties(BindingFlags.Public | BindingFlags.Instance | BindingFlags.FlattenHierarchy);
        foreach (var prop in properties)
        {
            var propValue = prop.GetValue(obj);
            var propType = prop.PropertyType;
            var defaultValue = propType.IsValueType ? Activator.CreateInstance(propType) : null;

            yield return (prop.Name, propValue, defaultValue);
        }

        var fields = type.GetFields(BindingFlags.Public | BindingFlags.Instance | BindingFlags.FlattenHierarchy);
        foreach (var field in fields)
        {
            var fieldValue = field.GetValue(obj);
            var fieldType = field.FieldType;
            var defaultValue = fieldType.IsValueType ? Activator.CreateInstance(fieldType) : null;

            yield return (field.Name, fieldValue, defaultValue);
        }
    }

    private static string GetPropInitializers(object? obj)
    {
        if (obj is null)
        {
            return "";
        }

        var result = new StringBuilder();
        var properties = GetFieldsAndProperties(obj);
        foreach ((string name, object? value, object? defaultValue) in properties)
        {
            if (value is not null && !value.Equals(defaultValue))
            {
                result.Append($"{name} = {value}, ");
            }
        }

        if (result.Length > 0)
        {
            result.Length -= 2; // remove the trailing comma and space: ", "
        }

        return result.ToString();
    }

    private static string GetSourceCodeDestination([CallerFilePath] string sourceCodePath = null)
    {
        var i = sourceCodePath.LastIndexOf(@"\Src\");
        if (i >= 0)
        {
            var sourcePath = sourceCodePath.Substring(0, i + @"\Src\".Length);
            return Path.Combine(sourcePath, "Sequences");
        }
        i = sourceCodePath.LastIndexOf(@"\Program.cs");
        if (i >= 0)
        {
            var sourcePath = sourceCodePath.Substring(0, i);
            return Path.Combine(sourcePath, "Src", "Sequences");
        }
        return "";
    }

    private static void SaveFile(string sequenceName, string code)
    {
        var destinationFolder = GetSourceCodeDestination();
        if (!Directory.Exists(destinationFolder))
        {
            Console.WriteLine("Unable to save new sequence code because destination folder doesn't exist: " + destinationFolder);
            return;
        }
        File.WriteAllText(Path.Combine(destinationFolder, $"{sequenceName}.cs"), code.ToString());
    }
}
