using System.Runtime.ConstrainedExecution;
using System.Text;
using Beater.Sampled;
using static System.Net.Mime.MediaTypeNames;

namespace Beater;

public static partial class Program
{
    public static void Main()
    {
        GracefulShutdown.Subscribe(TcpTransport.Close);

        try
        {
            // TODO: next session:
            /// when injecting sequences <see cref="AutoGenerated_seq20260508234907"/>, extend delays of yielding sounds

            /// TODO: eliminate <see cref="FollowPreviousSoundStrategy"/> - because it's just a convenience UI wrapper that allows to define chain of sounds as a flat list
            //  (except for SequenceEnd which is a special case that goes after the last sound in a sequence)

            // question: who should be responsible for looking around the current sound? the strategy of this sound or sequence generator?
            // probably sequence generator should provide a list of sounds near the current sound so that the strategy of that sound can take its own decisions
            // (for example if it needs to increase delay before the leader)
            // why do we need this? because if we want to inject a sequence between two sounds, the follower should be able to decide if it needs to increase
            // its delay before the leader or not, depending on the length of the inserted sequence.
            // question: how do we know if the follower before which a new sound was injected should increase its delay or remain with the same delay?

            // TODO: rename Strategy to Gene?

            // TODO 1:   implement zavitushki idea (tree of micro rhythmes following specific sounds of a sequence)
            // TODO 1.1: think about placeholders for sequences injected into the main sequence - the main sequence will be expandable and depend on the length of injected children sequences.
            // if a sequence is injected between followers: how existing follower should decide if it's delay X (configured for a previous leader) is still relevant, 
            // or it's not enough and it should use a different delay if injected sequence between the leader and the follower takes longer time than X

            // question: how do we track that leader has changed? should each sound have a history of leaders between iterations?

            // TODO: add unit test for appending one sequence to another without container(3rd) sequence (think about expected output)

            // TODO 2:
            // after a small sequence is inserted between two sounds, previous follower changes its leader, gradually increases the distance until the same distance is reached as from the previous leader
            // (like a car entered from another lane before another car)


            var player = new ConsoleKeyPlayer();
            player.PlayRepeated(AutoGenerated_seq20260508234907.GetSequence()).Wait();

            //var seq1 = SlowBeat.GetSequence1();
            //var three = new PrimitiveSequences.Repeat(new SoundDesign("ts5")) { Count = 3, Interval = 200, DelayAfterLeader = 100 };
            //var square = new PrimitiveSequences.Repeat(new SoundDesign("ts5"), "square") { Count = 8, Interval = seq1.Interval / 8 };
            //seq1.Combine(square);
            //seq1.Leader.FindByTag("end")?.Followers.Add(three.Leader);
            //player.PlayRepeated(seq1).Wait();

            //player.PlayRepeated(SlowBeat.GetSequence1()).Wait();
            //player.PlayRepeated(SlowBeat.GetSequence2()).Wait();
            //player.PlayRepeated(SlowBeat.GetSequence3()).Wait();
            //player.PlayRepeated(SlowBeat.GetSequence4()).Wait();
            //player.PlayRepeated(SlowBeat.GetSequence5()).Wait();

            //var seque = Noe_Solange_Home_DJCounselling.GetSequence();
            //player.PlayRepeated(seque).Wait();

            // player.PlayRepeated(SlowBeat.WithMovingSequenceBetweenGroups()).Wait();
            player.Listen();
            player.PrintFormatted();
            player.SaveSequence();
            player.SaveCode();
            player.PlayRepeated().Wait();

            using (var test = new SequencePlayerExample().Init())
            {
                test.Run().Wait();
            }
            Console.WriteLine("done");
        }
        catch (Exception ex)
        {
            Console.WriteLine(ex);
        }
    }
}