namespace Beater;

public abstract class AbstractStrategy
{
    /// <summary>
    /// Time to wait after the leader sound before starting to play the first follower or the whole loop (in case of repeated sounds).
    /// </summary>
    public int DelayAfterLeader { get; set; }

    /// <summary>
    /// Total number of times this strategy was checked and called (including skipped calls) starting from 1.
    /// NOTE: this counter is related to the strategy, not to the sound itself
    /// (e.g. for repeat strategy it will count number of loops, not total number of sounds in all loops)
    /// </summary>
    protected int CheckedTimes;

    /// <summary>
    /// Number of times when this strategy was actually played (not skipped).
    /// </summary>
    protected int CalledTimes;

    /// <summary>
    /// The sound will be played every X-th time:
    ///   1 - every time without skipping
    ///   2 - at even times (2,4,6...), while all odd times (1,3,5...) will be skipped.
    /// NOTE: this counter is related to the strategy, not to the sound itself.
    /// </summary>
    public int PlayEveryX = 1; // play every time by default

    /// <summary>
    /// The sound will be played every X-th time within repeated range, for example:
    ///  3/4 - each 3rd time will be played out of every 4.
    /// NOTE: this counter is related to the strategy, not to the sound itself.
    /// </summary>
    public string? PlayEveryXOutOf;

    /// <summary>
    /// Will replace current sound with an empty sound preserving the same followers, for example:
    ///  3/4 - each 3rd time out of every 4 will be silenced.
    /// NOTE: this counter is related to the strategy, not to the sound itself.
    /// </summary>
    public string? SilenceEveryXOutOf;

    /// <summary>
    /// An entry point to generate sequence of sounds of leader/follower.
    /// </summary>
    /// <param name="previousSounds">Sequence of previous sounds (if any), from which the generated sequence will continue.</param>
    public Sequence GenerateSequence(Sound sound, Sequence? previousSounds = null)
    {
        sound = sound with { /* clone */ };
        sound.SetLeader();

        CheckedTimes++;
        if (IsSkipped())
        {
            // skip
            return new();
        }

        if (IsSilenced())
        {
            sound = sound with { IsSilenced = true };
        }

        CalledTimes++;
        return GenerateSequenceFor(sound, previousSounds);
    }

    protected abstract Sequence GenerateSequenceFor(Sound leader, Sequence? previousSounds = null);

    private bool IsSilenced()
    {
        if (!SilenceEveryXOutOf.IsNullOrEmpty())
        {
            return IsXOutOf(SilenceEveryXOutOf, CheckedTimes);
        }
        return false;
    }

    private bool IsSkipped()
    {
        if (!PlayEveryXOutOf.IsNullOrEmpty())
        {
            return !IsXOutOf(PlayEveryXOutOf, CheckedTimes);
        }

        // count every call
        return CheckedTimes % PlayEveryX > 0;
    }

    protected bool IsXOutOf(string xOutOfY, int x)
    {
        // count calls within loop (for example, every 3rd time within repeated range of 4)
        var fraction = Numbers.GetFraction(xOutOfY);
        var playEveryX = fraction.Numerator;
        var range = fraction.Denominator;
        var iterationNumber = (x - 1) / range;
        var calledTimesInRange = x - (range * iterationNumber);

        return calledTimesInRange == playEveryX;
    }

    protected void AddFollowers(Sound leader, Sequence sequence)
    {
        if (leader.Followers.Count == 0)
        {
            return;
        }

        var mixedSequence = new Sequence();
        foreach (var follower in leader.Followers)
        {
            // NOTE: separate followers are played independently to allow overlapping sequences (mixed together)
            var followerSequence = follower.Strategy.GenerateSequence(follower, mixedSequence);
            mixedSequence.AddRange(followerSequence);
        }

        foreach (var mixedSound in mixedSequence)
        {
            // shift timestamp relatively to the leader (so that each sound will have an absolute position from the beginning of the whole sequence):
            mixedSound.Timestamp += leader.Timestamp;
        }

        // mix sequences generated by different followers:
        mixedSequence.Sort((a, b) => a.Timestamp.CompareTo(b.Timestamp));

        sequence.AddRange(mixedSequence);
    }
}