namespace Beater;

public abstract class AbstractStrategy
{
    /// <summary>
    /// Time to wait after the leader sound before starting to play the first follower or the whole loop (in case of repeated sounds).
    /// </summary>
    public int DelayAfterLeader { get; set; }

    /// <summary>
    /// Total number of times this strategy was checked and called (including skipped calls).
    /// NOTE: this counter is related to the strategy, not to the sound itself
    /// (e.g. for repeat strategy it will count number of loops, not total number of sounds in all loops)
    /// </summary>
    public int CheckedTimes;

    /// <summary>
    /// Number of times when this strategy was actually played (not skipped).
    /// </summary>
    public int CalledTimes;

    /// <summary>
    /// If X is integer, the sound will be played every X-th time:
    ///   1 - every time without skipping
    ///   2 - at even times (2,4,6...), while all odd times (1,3,5...) will be skipped.
    /// If X is a fraction, the sound will be played every X-th time within repeated range, for example:
    ///  3/4 - each 3rd time will be played out of every 4.
    /// </summary>
    public double PlayEveryX = 1; // play every time by default

    /// <summary>
    /// An entry point to generate sequence of messages of leader/follower.
    /// </summary>
    public List<SequenceMessage> GenerateSequence(Sound sound)
    {
        sound.SetLeader();

        CheckedTimes++;
        if (IsSkipped())
        {
            // skip
            return new();
        }

        CalledTimes++;
        return GenerateSequenceFor(sound);
    }

    private bool IsSkipped()
    {
        if (Numbers.IsInteger(PlayEveryX))
        {
            // count every call
            return CheckedTimes % PlayEveryX > 0;
        }

        // count calls within loop (for example, every 3rd time within repeated range of 4)
        var fraction = Numbers.GetFraction(PlayEveryX);
        var playEveryX = fraction.Numerator;
        var range = fraction.Denominator;
        var iterationNumber = (CheckedTimes - 1) / range;
        var calledTimesInRange = CheckedTimes - (range * iterationNumber);

        if (playEveryX == 1)
        {
            // 1 is a special case (because all numbers can be divided by 1)
            // let's just check the remainder of dividing by range:
            return calledTimesInRange % range != 1;
        }
        return calledTimesInRange % playEveryX > 0;
    }

    protected abstract List<SequenceMessage> GenerateSequenceFor(Sound sound);

    protected List<SequenceMessage> GenerateFollowersSequence(Sound sound, int currentTimestamp)
    {
        var mixedSequence = new List<SequenceMessage>();
        foreach (var follower in sound.Followers)
        {
            // NOTE: separate followers are played independently to allow overlapping sequences (mixed together)
            var sequence = follower.Strategy.GenerateSequence(follower);
            foreach (var msg in sequence)
            {
                // shift timestamp relatively to the beginning of the whole sequence (to be able to mix sequences generated by different followers)
                msg.Timestamp += currentTimestamp;
                mixedSequence.Add(msg);
            }
        }

        mixedSequence.Sort((a, b) => a.Timestamp.CompareTo(b.Timestamp));

        return mixedSequence;
    }
}