
namespace Beater;

public class Strategy
{
    /// <summary>
    /// Time to wait after the leader sound before starting to play the first follower or the whole loop (in case of repeated sounds).
    /// </summary>
    public int DelayAfterLeader { get; set; }

    public virtual List<SequenceMessage> GenerateSequence(Sound sound)
    {
        return new();
    }

    protected List<SequenceMessage> GenerateFollowersSequence(Sound sound, int currentTimestamp)
    {
        var mixedSequence = new List<SequenceMessage>();
        foreach (var follower in sound.Followers)
        {
            // NOTE: separate followers are played independently and may have overlapping sequences (mixed together)
            var sequence = follower.Strategy.GenerateSequence(follower);
            foreach (var msg in sequence)
            {
                // shift timestamp relatively to the beginning of the whole sequence (to be able to mix sequences generated by different followers)
                msg.Timestamp += currentTimestamp;
                mixedSequence.Add(msg);
            }
        }

        mixedSequence.Sort((a, b) => a.Timestamp.CompareTo(b.Timestamp));

        return mixedSequence;
    }
}

public class RepeatStrategy : Strategy
{
    public int Every { get; set; }
    public int Interval { get; set; }

    public override List<SequenceMessage> GenerateSequence(Sound sound)
    {
        var sequence = new List<SequenceMessage>();
        for (int i = 0; i < Every; i++)
        {
            var msg = new SequenceMessage(sound.Name)
            {
                DelayBefore = i == 0 ? DelayAfterLeader : 0, // we need to add a delay before the first sound because its leader is added with 0 delay
                DelayAfter = 0, // followers' delays will intersect with leader's delay
                Timestamp = DelayAfterLeader + (i * Interval),
            };
            sequence.Add(msg);

            var followersSequence = GenerateFollowersSequence(sound, msg.Timestamp);
            if (followersSequence.Count > 0)
            {
                sequence.AddRange(followersSequence);
            }

            var followersDelay = followersSequence.Sum(x => x.DelayBefore + x.DelayAfter);
            if (followersDelay < Interval)
            {
                // add remaining delay so that each loop duration will be the same (even the last one when we don't have any sound afterwards)
                sequence.Last().DelayAfter += Interval - followersDelay;
            }
        }

        return sequence;
    }
}

public class PlayOnceStrategy : Strategy
{
    public override List<SequenceMessage> GenerateSequence(Sound sound)
    {
        var msg = new SequenceMessage(sound.Name)
        {
            DelayBefore = DelayAfterLeader, // we need to add a delay before current sound because its leader is added with 0 delay
            Timestamp = DelayAfterLeader,
        };

        var sequence = new List<SequenceMessage>() { msg };
        if (sound.Followers.Count > 0)
        {
            sequence.AddRange(GenerateFollowersSequence(sound, msg.Timestamp));
        }

        return sequence;
    }
}