using Microsoft.VisualBasic;

namespace Beater;

public abstract class Strategy
{
    /// <summary>
    /// Time to wait after the leader sound before starting to play the first follower or the whole loop (in case of repeated sounds).
    /// </summary>
    public int DelayAfterLeader { get; set; }

    public int CalledTimes;
    public int PlayEveryX = 1; // play every time

    public List<SequenceMessage> GenerateSequence(Sound sound)
    {
        CalledTimes++;
        if (CalledTimes % PlayEveryX > 0)
        {
            // skip
            return new();
        }

        return GenerateSequenceFor(sound);
    }

    protected abstract List<SequenceMessage> GenerateSequenceFor(Sound sound);

    protected List<SequenceMessage> GenerateFollowersSequence(Sound sound, int currentTimestamp)
    {
        var mixedSequence = new List<SequenceMessage>();
        foreach (var follower in sound.Followers)
        {
            // NOTE: separate followers are played independently and may have overlapping sequences (mixed together)
            var sequence = follower.Strategy.GenerateSequence(follower);
            foreach (var msg in sequence)
            {
                // shift timestamp relatively to the beginning of the whole sequence (to be able to mix sequences generated by different followers)
                msg.Timestamp += currentTimestamp;
                mixedSequence.Add(msg);
            }
        }

        mixedSequence.Sort((a, b) => a.Timestamp.CompareTo(b.Timestamp));

        return mixedSequence;
    }
}

public class RepeatStrategy : Strategy
{
    public int Count;
    public int Interval;
    public int LinearIncrement;
    private int _previousIterval;

    protected override List<SequenceMessage> GenerateSequenceFor(Sound sound)
    {
        var sequence = new List<SequenceMessage>();
        for (int i = 0; i < Count; i++)
        {
            var msg = new SequenceMessage(sound.Name)
            {
                Timestamp = DelayAfterLeader + CalculateInterval(i),
            };
            sequence.Add(msg);

            if (sound.Followers.Count > 0)
            {
                sequence.AddRange(GenerateFollowersSequence(sound, msg.Timestamp));
            }
        }

        _previousIterval = 0;

        return sequence;
    }

    private int CalculateInterval(int i)
    {
        if (LinearIncrement == 0)
        {
            return i * Interval;
        }

        if (i == 0)
        {
            // this is the first increment
            return 0;
        }

        return _previousIterval += Interval + (i - 1) * LinearIncrement;
    }
}

public class PlayOnceStrategy : Strategy
{
    protected override List<SequenceMessage> GenerateSequenceFor(Sound sound)
    {
        var msg = new SequenceMessage(sound.Name)
        {
            Timestamp = DelayAfterLeader,
        };

        var sequence = new List<SequenceMessage>() { msg };
        if (sound.Followers.Count > 0)
        {
            sequence.AddRange(GenerateFollowersSequence(sound, msg.Timestamp));
        }

        return sequence;
    }
}